### PR TITLE
feat(fan): add legacy speed support

### PR DESCRIPTION
**Pull request by clshortfuse**
References: 

[Fan (fs) Standard Instruction Set](https://developer.tuya.com/en/docs/iot/f?id=K9gf45vs7vkge)

### CODE REVIEW

**Comment by tetsuo55** [comment]
I tested this on my FSD, ceiling fan light but unfortunately this doesn't fix the speed for it.

Looking at the fs instruction set makes if clear that it wasn't going to work as the values look different.

Mine are
code": "fan_speed",
"type": "Integer",
"values": "{"unit":"","min":1,"max":6,"scale":0,"step":1}"

**Comment by clshortfuse** [comment]
@tetsuo55 It works for my fan, but mine reports a range of string values. This is consistent with official documentation:

image

It looks like your fan is a completely different type (`fsd`): https://developer.tuya.com/en/docs/iot/f?id=Kaof8fwdfzz9y

I can add support for `fsd`, but there's not listed as a supported type.

````js
TUYA_SUPPORT_TYPE = {
    "fs",  # Fan
    "kj",  # Air Purifier
}
```

**Comment by tetsuo55** [comment]
> @tetsuo55 It works for my fan, but mine reports a range of string values. This is consistent with official documentation:
> 
> image
> 
> It looks like your fan is a completely different type (`fsd`): https://developer.tuya.com/en/docs/iot/f?id=Kaof8fwdfzz9y
> 
> I can add support for `fsd`, but there's not currently listed as a supported type.
> 
> ```js
> TUYA_SUPPORT_TYPE = {
>     "fs",  # Fan
>     "kj",  # Air Purifier
> }
> ```

I added it in https://github.com/tuya/tuya-home-assistant/pull/358 but it hasn't been merged yet, probably because nothing works beyond on/off

**Comment by tetsuo55** [comment]
@clshortfuse 

We managed to get my fan speeds working in https://github.com/tuya/tuya-home-assistant/pull/490 (at the time I'm writing this there is one change missing in the pr itself but mentioned in the comments).

That pr should also work for your fan, could you test?

**Comment by zlinoliver** [comment]
Hi @clshortfuse , the Tuya developer team really appreciates your contributions and efforts to this Tuya v2 integration project. As we stop maintaining it now, please help to recreate your pull request in the Home Assistant Core repository: <https://github.com/home-assistant/core/tree/dev/homeassistant/components/tuya>

**Pull request closed without merging**
