### PR TITLE
Robot vacuum adds: switch voice, locate, paused and docking status and attributes clean area, clean time, clean record and status original

### PR DESCRIPTION
**Pull request by dougiteixeira**
Robot vacuum adds: switch voice, locate, paused and docking status and attributes clean area, clean time, clean record and status original

### CODE REVIEW

**Comment by dougiteixeira** [comment]
@tsutsuku Can you review it for me? Thanks

**Comment by tsutsuku** [comment]
@dougiteixeira Can you provide your robot vacuum device specifications? Some DPs in your PR are not like the documentation provided.

**Comment by dougiteixeira** [comment]
@tsutsuku device id: ebced93a821db35059xhsx

**Comment by dougiteixeira** [comment]
> @dougiteixeira Can you provide your robot vacuum device specifications? Some DPs in your PR are not like the documentation provided.

@tsutsuku API response:

```
{
   "result": {
    "active_time": 1630450820,
    "biz_type": 0,
    "category": "sd",
    "create_time": 1629488714,
    "icon": "smart/icon/ay1567915509987ktVbv/1e7c3bc6db8248416a8d99db689aa689.png",
    "id": "<removed>",
    "ip": "<removed>",
    "lat": "<removed>",
    "local_key": "<removed>",
    "lon": "<removed>",
    "model": "XR011R-0006",
    "name": "Robô Aspirador",
    "online": true,
    "owner_id": "39625796",
    "product_id": "qj62eqcp4c6fdypo",
    "product_name": "Robotic Vacuum Cleaner",
    "status": [
      {
        "code": "power",
        "value": true
      },
      {
        "code": "fault",
        "value": 0
      },
      {
        "code": "electricity_left",
        "value": 100
      },
      {
        "code": "power_go",
        "value": false
      },
      {
        "code": "direction_control",
        "value": "foward"
      },
      {
        "code": "mode",
        "value": "standby"
      },
      {
        "code": "status",
        "value": "chargecompleted"
      },
      {
        "code": "suction",
        "value": "normal"
      },
      {
        "code": "voice_switch",
        "value": false
      },
      {
        "code": "clean_area",
        "value": 42
      },
      {
        "code": "clean_time",
        "value": 46
      },
      {
        "code": "clean_record",
        "value": "04604200265"
      }
    ],
    "sub": false,
    "time_zone": "-03:00",
    "uid": "<removed>",
    "update_time": 1630501063,
    "uuid": "<removed>"
  },
  "success": true,
  "t": 1630535804321
}
```

Thanks!

**Comment by carlosvroque** [comment]
I've tested these changes with my vacuum and they're amazing, thanks a lot!

**Review by tsutsuku — APPROVED** [review]
Thank you for your contribution.

**Pull request merged**
