### PR TITLE
Coffee Maker

### PR DESCRIPTION
**Pull request by Sthopeless**
[Coffee Maker](https://developer.tuya.com/en/docs/iot/f?id=K9gf4701ox167)

```
    "category": "kfj",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "start",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "pause",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"espresso\",\"americano\",\"machiatto\",\"caffe_latte\",\"cafe_mocha\",\"cappuccino\"]}"
      },
      {
        "code": "material",
        "type": "Enum",
        "values": "{\"range\":[\"bean\",\"powder\"]}"
      },
      {
        "code": "concentration_set",
        "type": "Enum",
        "values": "{\"range\":[\"regular\",\"middle\",\"bold\"]}"
      },
      {
        "code": "warm",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "warm_time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cup_number",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"]}"
      },
      {
        "code": "cleaning",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "water_set",
        "type": "Integer",
        "values": "{\"unit\":\"ml\",\"min\":0,\"max\":500,\"scale\":0,\"step\":1}"
      },
      {
        "code": "powder_set",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":24,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cloud_recipe_number",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999999,\"scale\":0,\"step\":1}"
      }
```

### CODE REVIEW

**Comment by tsutsuku** [comment]
@Sthopeless Have you tried this with the real device?

**Comment by Sthopeless** [comment]
@tsutsuku if you can link me one I would be glad 🤣 unfortunately I haven't found.
It's a test device from iot cloud

**Comment by tsutsuku** [comment]
@Sthopeless Can you fix the conflicting files, so we can merge the PR. Next version will release soon.

**Comment by Sthopeless** [comment]
done @tsutsuku

**Pull request merged**
